### ISSUE TITLE
Compression groups are nested in i3

### ISSUE THREAD

**Issue by depascalis** [fluxionary/minetest-moreblocks#13]
Moving the issue from the [PR comment](https://github.com/minetest-mods/moreblocks/pull/191#issuecomment-1345406265) to here.

Compression groups are being nested in i3. See image bellow where one compressed group of slopes is nested under the expanded group.

![image](https://user-images.githubusercontent.com/33980634/206879040-902c9a28-775f-4638-8102-4194259385b6.png)

_Previous comment by @fluxionary_ 
>  I will work on understanding why that's behaving wrong, but i3 is not designed to work well w/ other mods, and I won't promise to try to fix it.

**Comment by fluxionary** [comment]
ah, just noticed this. as mentioned in PR, i don't see this behavior locally, can you give me more info on which mods (and versions of the mods) you're using?

**Comment by fluxionary** [comment]
finally figured out what was going on, it was due to i3 making assumptions about what the compression groups should be for stairsplus. this should be fixed in the most recent commit of this repo.
