### ISSUE TITLE
unnecessary aliases

### ISSUE THREAD

**Issue by Niklp09** [fluxionary/minetest-moreblocks#18]
The alias api also registers aliases for `stairs:*` blocks that never existed
Example from `minetest.registered_aliases`:
`["stairs:micro_silver_sandstone_block"] = "default:micro_silver_sandstone_block_8",`
https://github.com/fluxionary/minetest-moreblocks/blob/master/stairsplus_legacy/default.lua#L52
But the mtg stairs only support 4 of the 49 stairsplus stairs, so 45 aliases per block are useless.
Or have I missed something?

**Comment by fluxionary** [comment]
https://github.com/fluxionary/minetest-moreblocks/commit/c6134786c0738ce302aec52d5059dca66c569e1c

does that look right?

**Comment by Niklp09** [comment]
quickly grepped over the alias list, works
2385 aliases less with my modpack
