### ISSUE TITLE
Give shapes same group than block

### ISSUE THREAD

**Issue by mowgli** [fluxionary/minetest-moreblocks#20]
Currently, shapes do not have the groups shared with the block.

For example, all snow has snowy group but not the snow shapes/pannels. That makes it difficult to select them at once.

Solution would be easy, add the group:snowy , group:stone, … to the shaped blocks.

**Comment by fluxionary** [comment]
whoops, somehow this slipped under my radar for seven months, i apologize! 

by default, groups are inherited in a way, by augmenting them w/ the shape. e.g. if you have a wooden slab, it will be in the group "slab_wood_8". 

there's an API for managing group inheritance: https://github.com/fluxionary/minetest-moreblocks/blob/master/stairsplus/api/group_filters.lua

basically, it gives you 3 ways to override the default inheritance method:
1. ignore the group - it isn't inherited at all
2. pass-through - the group is inherited as-is, without the shape affixes. this great for e.g. damage and digging time defining groups. 
3. scale - reduce the value of the group in proportion to how many "node eighths". this is mostly for a couple builtin things like the "bouncy" group.

you can see the default examples here: https://github.com/fluxionary/minetest-moreblocks/tree/master/stairsplus/groups

the reason i don't want e.g. the "stone" group to be a pass-through group is that it's used in a lot of crafting recipes. suddenly, you can then use stone microblocks in a lot of recipes that used to require full stones. 

if there's something you think should still change, let me know.

**Comment by fluxionary** [comment]
i did an audit of (a lot but not all)  minetest mods, and didn't find any indication that the snowy group was used in crafting recipes. the only uses were related to spawning mobs, and whether trees should grow with snow on them. given that, i've added snowy to the passthrough groups from minetest game. let me know if there's other similar groups you think should get the same treatment.
