### ISSUE TITLE
mods using circular_saw global or other weirdness

### ISSUE THREAD

**Issue by fluxionary** [fluxionary/minetest-moreblocks#9]
* [x] [Replacer](https://content.minetest.net/packages/Sokomine/replacer/) by Sokomine
  seems to be gated to use the old `circular_saw` *mod* so ... not gonna touch this. 
* [x] [Replacer](https://github.com/SwissalpS/replacer) by SwissalpS
  no crash, but we can add compatibility: https://github.com/SwissalpS/replacer/pull/44
* [x] [i3](https://content.minetest.net/packages/jp/i3/) by jp
  ~~i3 depends on moreblocks, creating a circular dependency~~ not sure how i reached that conclusion, it doesn't. i don't understand what exactly i3 is trying to do w/ moreblocks, but it doesn't make direct use of it. 
* [x] [redef](https://content.minetest.net/packages/Linuxdirk/redef/) by Linuxdirk
  actually, we now manage using world-aligned textures ourselves, so nothing to fix here. 
* [x] [mtinfo](https://github.com/BuckarooBanzay/mtinfo/pull/91) by Buckaroo
  no crash, made a PR to add compatibility https://github.com/BuckarooBanzay/mtinfo/pull/91 . 
* [x] [invsaw](https://forum.minetest.net/viewtopic.php?t=14736) by cheapie
  i ended up just [adding invsaw to moreblocks](https://github.com/minetest-mods/moreblocks/pull/191/commits/5990d7c6a458cbe3822176df38551de56deca4c5), as it required pretty much a total rewrite. 

-----------------------
known issues that won't be fixed:
* [x] [Roads](https://content.minetest.net/packages/cheapie/roads/) by cheapie
  crash, tries to use e.g. `register_stair_slab_panel_micro`
* [x] [Quartz](https://content.minetest.net/packages/Evergreen/quartz/) by Evergreen
  no crash, but didn't even work w/ old moreblocks
* [x] [Emeralds](https://github.com/CC10MAGIC/emeralds)
  no crash, but didn't even work w/ old moreblocks
* [x] [plasticbox](https://content.minetest.net/packages/Starbeamrainbowlabs/plasticbox/)
  tries to register w/ an invalid paramtype2 (color). this is unfixable. 
* [x] [Basic Streets](https://content.minetest.net/packages/BuckarooBanzay/basic_streets/) by BuckarooBanzai
  tries to register w/ an invalid paramtype2 (colorwallmounted). this is unfixable. 
* [x] [coloredwood](https://content.minetest.net/packages/VanessaE/coloredwood/)
  crashes - tries to register stairs with no base node. this is unfixable.

**Comment by fluxionary** [comment]
marking `Roads` as done as it currently doesn't even work with the current version of moreblocks

**Comment by fluxionary** [comment]
quartz and emerald also aren't compatible w/ the current version of moreblocks

**Comment by Niklp09** [comment]
What about invsaw? https://cheapiesystems.com/git/invsaw/

**Comment by fluxionary** [comment]
> What about invsaw? https://cheapiesystems.com/git/invsaw/

good catch, i'll investigate. not sure how to PR cheapie tho... but i think i've done so before.

**Comment by fluxionary** [comment]
ended up just adding invsaw to this repo, because a whole lot of stuff needed to be reworked.
